services:
  server:
    env_file: .env
    container_name: dev_sever
    build:
      dockerfile: Dockerfile
      context: .
      target: development
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run start:dev
    ports:
      - ${PORT}:${PORT}
    environment:
      - NODE_ENV=development

    depends_on:
      - db
    networks:
      - internet
      - postgres-network

  db:
    env_file: .env
    container_name: dev_db
    build:
      context: ./db
    restart: always
    user: postgres
    volumes:
      - PG-DATA:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB={DB_NAME}
      - POSTGRES_HOST={DB_HOST}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_PORT=${DB_PORT}
    ports:
      - ${DB_PORT}:${DB_PORT}
    networks:
      - postgres-network

  # pg-admin:
  #   image: dpage/pgadmin4
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: dbuset@example.com
  #     PGADMIN_DEFAULT_USERNAME: ${DB_USER}
  #     PGADMIN_DEFAULT_PASSWORD: ${DB_PASSWORD}

  #   ports:
  #     - '8080:80'
  #   restart: unless-stopped
  #   networks:
  #     - postgres-network
  #     - internet

volumes:
  ignore:
  PG-DATA:

networks:
  internet:
    driver: bridge
    internal: true
  postgres-network:
    driver: bridge
